// kant version
// const http = require('http');
//
// var server = new http.Server();
//
// server.listen(1337, '127.0.0.1');
//
//
// var counter = 0;
// server.on('request', function(req, res){
//   res.setHeader("Content-Type", "application/json; charset=utf-8");
//   res.end("привет.мир2" + ++counter)
// })





// node page version
// const http = require('http');
//
// http.createServer(function(req,res){
//   res.writeHead(200, {'Content-Type': 'text/plain'});
//   res.end("Hello World\n")
// }).listen(1337, '127.0.0.1');
//


// socket server

// var net = require('net');
//
// var server = net.createServer(function(socket){
// socket.write('Echo server\r\n');
// socket.pipe(socket);
// });
// server.listen(1337, '127.0.0.1');



// kant version
const http = require('http');

var server = new http.Server();
// (http.server) inherits from (net.server) which inherits from (EventEmitter())

// all events are generated by emit, so to take control over it, rewrite it
var emit = server.emit;
server.emit = function(event /*, arg1, arg2, req, res */) {
  console.log(event);
  emit.apply(server, arguments)
}
server.listen(1337, '127.0.0.1');
